version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: api_nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./api:/var/www/api
      - ./api/nginx/conf.d/:/etc/nginx/conf.d/
      - ./api/certbot/conf:/etc/letsencrypt
      - ./api/certbot/www:/var/www/certbot
    networks:
      - api
  certbot:
    image: certbot/certbot
    container_name: api_certbot
    volumes:
      - ./api/supervisor:/etc/supervisor
      - ./api/certbot/conf:/etc/letsencrypt
      - ./api/certbot/www:/var/www/certbot
  laravel:
    container_name: api_laravel
    tty: true
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api
    networks:
      - api
    depends_on:
      - pgsql
  pgsql:
    container_name: api_postgres
    restart: unless-stopped
    image: postgres:14
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      PGUSER: 'test'
      PGPASSWORD: 'test'
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
    volumes:
      - 'sovok-pgsql:/var/lib/postgresql/data'
    networks:
      - api
  python_webhooks:
    container_name: python_webhooks
    restart: unless-stopped
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:56733:80'
    volumes:
      - './flask:/app'
    networks:
      - api
  neural_network:
    container_name: neural_network
    restart: unless-stopped
    build:
      context: ./neural_network
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:56734:80'
    volumes:
      - './neural_network:/app'
    networks:
      - api
  python_bot:
    container_name: python_bot
    restart: unless-stopped
    build:
      context: ./bot
      dockerfile: Dockerfile
    networks:
      - api
networks:
  api:
    driver: bridge
volumes:
  sovok-pgsql:
    driver: local