version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: sovok_nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/sovok
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - sovok
  certbot:
    image: certbot/certbot
    container_name: sovok_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  laravel:
    container_name: sovok_laravel
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/sovok
    networks:
      - sovok
    depends_on:
      - pgsql
  pgsql:
    container_name: sovok_postgres
    restart: unless-stopped
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      PGPASSWORD: 'sovok'
      POSTGRES_DB: 'sovok'
      POSTGRES_USER: 'sovok'
      POSTGRES_PASSWORD: 'sovok'
    volumes:
      - 'sovok-pgsql:/var/lib/postgresql/data'
    networks:
      - sovok
  python_webhooks:
    container_name: python_webhooks
    restart: unless-stopped
    build:
      context: ../flask
      dockerfile: Dockerfile
    ports:
      - '56733:80'
    volumes:
      - '../flask:/app'
networks:
  sovok:
    driver: bridge
volumes:
  sovok-pgsql:
    driver: local
